### PR TITLE
Fixes to make compatible with autocomplete in admin with cursor based pagination and circleci build process

### PR DESCRIPTION
**Pull request by lahuindai**

### CODE REVIEW

**Comment by a1tus** [comment]
Hello. Thank you for your PR. I was planning to release new version with python 3.10 and django 4.0 support (in fact it only affects setup.cfg). So it can be combined with your PR.

But there're a few questions:

1. Why did you remove `from .admin import CursorPaginatorAdmin  # noqa: F403` from init? It's there for short and explicit import and also backwards incompatible.
2. As I see now in django original `class Page(collections.abc.Sequence):` there're `has_previous` method (not `has_prev`). Is it a bug?

**Comment by lahuindai** [comment]
Hello @a1tus, thank you for checking it out. To answer your questions;

**Comment by a1tus** [comment]
1. That's strange because if django is its dependency it should be installed after it. I think we can make some workaround with lazy import or even simple try/except but... I didn't understand is it needed or not? =)
2. As I see in django source only `has_next` is used in autocomplete so it would be more safe to use `has_previous` so that it could be used like django's `Page`.

**Comment by lahuindai** [comment]
1. I think is because of the git import in requirements.txt rather than the module

**Comment by a1tus** [comment]
> Having both would mean support for either case ?
I just didn't understand phrase `The Pagination requires has_prev`. You mean django pagination? I just didn't find any `has_prev` methods in django sources.

**Comment by lahuindai** [comment]
This is what led me to add those functions

`File "/Users/./.virtualenvs/web/lib/python3.9/site-packages/django/views/generic/list.py", line 119, in get_context_data
paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, page_size)
File "/Users/./.virtualenvs/web/lib/python3.9/site-packages/django/views/generic/list.py", line 70, in paginate_queryset
return (paginator, page, page.object_list, page.has_other_pages())
AttributeError: 'AdminCursorPage' object has no attribute 'has_other_pages'`

Once I added that th next one was has_next followed by has_prev

**Comment by a1tus** [comment]
Thanks again, I've released a new version, check if it fits you now.

https://github.com/a1tus/django-admin-cursor-paginator/releases/tag/v0.1.2

**Pull request closed without merging**
